### ISSUE TITLE
HEAD request

### ISSUE THREAD

**Issue by pawelantczak** [dzikoysk/NanoMaven#1]
Hello.
Please consider adding HEAD request handling.
For some reason, Maven is performing such.

```
[04.10.2018 18:15:46.106][NanoHttpd Request Processor (#20)/DEBUG] /io/pivotal/rti4t-gemfire/3.1.0-v95/rti4t-gemfire-3.1.0-v95.pom | {} | HEAD | null | {expires=0, x-forwarded-proto=http, x-forwarded-for=87.207.77.132, pragma=no-cache, x-real-ip=87.207.77.132, remote-addr=91.185.185.169, http-client-ip=91.185.185.169, cache-store=no-store, host=maven.myatos.eu, connection=close, cache-control=no-cache, accept-encoding=gzip, user-agent=Apache-Maven/3.3.9 (Java 1.8.0_152-release; Mac OS X 10.14)}
/io/pivotal/rti4t-gemfire/3.1.0-v95/rti4t-gemfire-3.1.0-v95.pom HEAD
[04.10.2018 18:15:46.107][NanoHttpd Request Processor (#20)/ERROR] Unknown method: /io/pivotal/rti4t-gemfire/3.1.0-v95/rti4t-gemfire-3.1.0-v95.pom
Oct 04, 2018 6:15:46 PM fi.iki.elonen.NanoHTTPD$Response send
SEVERE: Could not send response to the client
java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.util.zip.GZIPOutputStream.finish(GZIPOutputStream.java:164)
	at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1665)
	at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1657)
	at fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:1624)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:957)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dzikoysk** [comment]
Thanks, HEAD requests should work in [1.0.6](https://github.com/dzikoysk/NanoMaven/releases)

**Comment by pawelantczak** [comment]
Wow. That was quick. Dzięki!
