### ISSUE TITLE
Invalid xml in maven-metadata-remote.xml while publishing snapshot

### ISSUE THREAD

**Issue by ruzkant** [dzikoysk/nanomaven#27]
Attempting to publish a snapshot results in the below exception in gradle due to the maven-metadata-remote.xml not containing valid xml...

metadata-remote.xml contains:

`
Empty build metadata
`

The Exception:

`
Caused by: org.sonatype.aether.RepositoryException: Could not parse metadata ..../build/tmp/publishJavaPublicationToNanoRepository/xx/xx/xxxx/xxxxx/1.53-SNAPSHOT/maven-metadata-remote.xml: only whitespace content allowed before start tag and not E (position: START_DOCUMENT seen E... @1:1) 
        at org.apache.maven.repository.internal.MavenMetadata.read(MavenMetadata.java:105)
        at org.apache.maven.repository.internal.MavenMetadata.merge(MavenMetadata.java:69)
        at org.sonatype.aether.impl.internal.DefaultDeployer.upload(DefaultDeployer.java:410)
        ... 57 more
Caused by: org.codehaus.plexus.util.xml.pull.XmlPullParserException: only whitespace content allowed before start tag and not E (position: START_DOCUMENT seen E... @1:1) 
        at org.codehaus.plexus.util.xml.pull.MXParser.parseProlog(MXParser.java:1528)
        at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1407)
        at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1105)
        at org.apache.maven.artifact.repository.metadata.io.xpp3.MetadataXpp3Reader.read(MetadataXpp3Reader.java:1193)
        at org.apache.maven.artifact.repository.metadata.io.xpp3.MetadataXpp3Reader.read(MetadataXpp3Reader.java:1122)
        at org.apache.maven.repository.internal.MavenMetadata.read(MavenMetadata.java:97)
        ... 59 more
`

**Comment by dzikoysk** [comment]
Try `2.1.2`. I've just tested it with a snapshot deploy and it works. There was a problem with deploying version that does not exist (during the first deploy)

**Comment by ruzkant** [comment]
@dzikoysk it does publish now but doesn't retrieve, so I opened up another item: #29
